import React, { useEffect, useState } from 'react'

const LoremIpsum = ({ length, ...props }) => {
	const paragraphs = length > 10 ? 10 : length < 0 ? 0 : length
	const loremIpsum = [
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus semper ipsum vitae nisi iaculis, eu aliquam ligula condimentum. Ut lacinia, nibh quis aliquet tempor, leo nulla gravida magna, eget suscipit metus nulla in erat. Curabitur efficitur risus et ornare volutpat. Etiam non luctus libero. Nullam feugiat nulla ac tellus condimentum tincidunt. Aliquam tempor pulvinar velit, ullamcorper dapibus tellus. Aliquam erat volutpat. Mauris id accumsan sem, quis dictum leo. Aenean lacinia odio at magna gravida tempor. Sed ac pharetra mauris. Nullam semper, diam lobortis sagittis iaculis, diam lectus egestas enim, at ornare ipsum mi sed nunc. Phasellus scelerisque justo et quam bibendum, ac porttitor erat eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porttitor dapibus nisi, eu interdum sapien.',

		'In hac habitasse platea dictumst. Cras id ligula sed tellus varius bibendum quis eu tortor. Duis vel euismod est. In ullamcorper sapien erat, eget vulputate urna ullamcorper et. Duis a ultricies purus. Donec nec lorem eleifend, fermentum augue et, interdum mi. Donec in hendrerit justo, et lobortis quam. Phasellus tincidunt porttitor mi. Mauris eros erat, scelerisque ac malesuada id, laoreet sit amet nisl. Curabitur pharetra facilisis mauris eget dapibus. Nam vestibulum eros a purus varius fermentum. Suspendisse potenti. In euismod nisl quis mi dapibus auctor. Nulla vehicula massa eget ultricies bibendum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam sem sapien, sagittis vel augue ut, placerat auctor odio.',

		'Pellentesque at pharetra neque. Aenean at porta lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam eros leo, bibendum id convallis vitae, consequat vitae mi. Donec dui ex, placerat fringilla fringilla nec, maximus ut tellus. Aliquam justo urna, auctor sit amet porta ut, pellentesque vel leo. Nulla ligula massa, posuere ac eros non, viverra eleifend ex. Nunc facilisis dictum dui, condimentum blandit nunc sollicitudin et. Duis ut magna mattis, fermentum turpis ut, lobortis dui. Mauris condimentum luctus lectus id congue. Morbi convallis mattis blandit. Donec eget interdum risus. Aenean cursus, ex id volutpat rutrum, odio lacus pretium turpis, sed pellentesque lectus odio ut leo.',

		'In tempor orci nec lobortis luctus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vivamus sapien metus, dignissim eget bibendum sit amet, pellentesque nec elit. Aenean posuere sapien a felis accumsan, sed malesuada sapien molestie. Maecenas consequat tortor eget dolor fringilla ultrices. Sed in lectus fermentum, ornare tellus quis, iaculis eros. Morbi in tempus justo. Fusce eu magna nec velit pellentesque mollis. Etiam ac dui et ex consectetur suscipit eget vel ligula. Curabitur sodales, nulla vitae venenatis ultrices, tellus sem placerat velit, eget tempor felis massa id massa. Pellentesque risus ante, ullamcorper sed leo a, pellentesque porttitor magna. Aliquam maximus mollis diam, id fringilla purus cursus ac.',
		
		'Ut diam nulla, rutrum vestibulum viverra a, laoreet nec arcu. Cras hendrerit vestibulum lectus, a accumsan massa auctor nec. Nam efficitur egestas sem, non scelerisque quam tristique id. Nullam mattis massa eu lorem consequat, et suscipit quam efficitur. Cras consequat in metus sit amet dignissim. Nullam id sodales orci. Ut fringilla non lectus eget posuere. Proin interdum iaculis maximus. Ut feugiat ornare arcu vitae ultricies. Duis efficitur elit vel sapien aliquet pretium. Vestibulum fermentum justo urna, sit amet maximus dui eleifend ac. Curabitur dictum scelerisque iaculis.',
		
		'Sed nec nisi vulputate, volutpat dui quis, luctus dui. Proin luctus eros nulla, vitae lacinia turpis ullamcorper sed. Duis malesuada in justo a porttitor. Ut pulvinar mi eget ligula lacinia gravida. Donec sagittis dictum leo et auctor. Nullam velit nunc, sagittis id dictum non, vehicula vestibulum metus. Phasellus aliquet eu lectus et auctor. Ut venenatis nec magna a congue. Nullam tincidunt dolor sit amet erat fringilla, pulvinar tincidunt dolor consequat. Nunc eu dolor non sem porta hendrerit non sit amet risus.',
		
		'Sed ut ipsum turpis. Maecenas rhoncus eu nunc id volutpat. Nam ut ullamcorper augue, ac fringilla eros. Nunc ac facilisis massa, sed placerat libero. Pellentesque diam erat, laoreet id lectus sed, semper congue massa. Proin viverra, velit non maximus interdum, dolor odio facilisis elit, quis ultricies elit elit vel ligula. Aliquam porta interdum risus ut aliquet. Proin sit amet auctor libero. Pellentesque lobortis at augue in fermentum. Donec id orci vel magna condimentum consequat. Aliquam vulputate auctor turpis, in dictum odio placerat a. Vivamus non lorem ac libero consequat vulputate. In posuere tempor lectus, sed convallis nisi. Aliquam libero arcu, porta ac commodo vitae, venenatis at massa. Curabitur rhoncus mauris et ornare pretium.',
		
		'Integer eget fringilla dui. Ut fermentum tortor eu nisi fermentum ornare. Curabitur laoreet mauris vel suscipit molestie. Quisque eu maximus sapien, sit amet eleifend dui. Pellentesque efficitur euismod eros, vel pretium risus tristique in. Curabitur varius elit blandit diam venenatis lacinia. Ut aliquet dui id tincidunt blandit. Donec aliquet purus commodo ex consectetur, nec tempus augue porta. Mauris lobortis, metus quis finibus aliquam, urna libero commodo ex, vel varius turpis sapien eu eros. Donec eget odio magna. Duis sed lorem odio. Suspendisse in consequat augue. Ut quis aliquam mi, at vulputate purus. In justo neque, molestie a lacinia nec, sagittis at odio.',
		
		'Aliquam erat volutpat. Proin nec commodo nulla. Etiam et laoreet neque. Nam vitae consectetur libero. Praesent dignissim, leo eget tristique fermentum, lacus enim gravida metus, eu eleifend sapien purus pellentesque tellus. Curabitur dapibus, est et imperdiet viverra, velit lorem condimentum purus, a elementum purus libero eu ligula. Maecenas at justo sollicitudin metus tempor pellentesque. Nullam nibh dolor, pulvinar in accumsan at, vulputate vitae felis. Cras et faucibus ipsum. Praesent at libero cursus magna tempus varius. Sed faucibus massa at scelerisque blandit. Maecenas mauris ex, viverra ac pulvinar id, pellentesque at purus.',
		
		'Vestibulum bibendum, leo eu commodo malesuada, enim enim scelerisque nunc, a mattis leo lacus ornare sem. Nullam a rhoncus metus. Curabitur vel venenatis metus. Integer ex nisl, sagittis pharetra efficitur auctor, tristique quis mauris. Fusce volutpat, neque eget facilisis sodales, neque augue pulvinar sapien, quis venenatis sem mi eu massa. Proin viverra euismod lectus eget varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed gravida id mi eu convallis. Ut venenatis at tortor et blandit. In consequat leo ut metus euismod facilisis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut porta non erat et faucibus. Ut sed ornare lorem.',
		
		'Vivamus ultricies, ligula id malesuada dapibus, enim sapien aliquet metus, in maximus mauris lorem nec ligula. Integer placerat est ut lacus tincidunt aliquam. Nullam venenatis libero nec vehicula hendrerit. Sed consequat vel dolor et aliquet. Integer ut nulla quis tellus bibendum tincidunt. Aenean pharetra sagittis suscipit. Praesent sit amet vehicula libero. Nullam nunc nulla, rhoncus et congue id, gravida vitae felis. Duis sit amet diam nunc. Cras vulputate tortor ligula, malesuada vehicula nisi egestas eget. Duis sit amet tincidunt turpis.',
		
		'Ut sit amet mauris elementum nisi aliquet aliquet ac ac felis. Nunc non tincidunt leo, in egestas mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent bibendum leo sed tellus vehicula efficitur. Nulla vehicula nunc nunc, id pharetra ligula hendrerit nec. Nullam a iaculis leo, non rhoncus nisl. Pellentesque in lectus sollicitudin, cursus ligula id, luctus magna. Nulla a ex quis urna rhoncus auctor. Integer quis felis pretium, varius diam eu, hendrerit nisl. Nam enim metus, porta vel dapibus sit amet, scelerisque eu augue. Phasellus gravida laoreet est vel vestibulum. Quisque in nulla lacinia, egestas orci sit amet, semper odio. Aenean ornare magna vel congue euismod. Nullam pharetra interdum ipsum at malesuada.',
		
		'Sed bibendum pellentesque justo malesuada bibendum. In faucibus egestas enim vitae varius. Etiam elit nisi, consectetur et elit id, vehicula ultricies eros. Pellentesque non suscipit dolor. Quisque nec blandit augue. Quisque quis orci quam. Nunc facilisis posuere iaculis. Integer lobortis nibh porta, tempor elit viverra, mattis lorem. In hac habitasse platea dictumst. Curabitur porttitor imperdiet pretium. Aliquam ut mattis est. Curabitur consequat, ex ut finibus dignissim, dolor ante elementum risus, at fringilla dui nulla et ante. Ut at nulla eget lorem dapibus iaculis. Proin consectetur mi ex, ut tincidunt lectus tincidunt commodo. Vestibulum eu sapien et diam accumsan vulputate ut ut lacus. Nunc eleifend eget metus ac venenatis.',
		
		'Curabitur luctus ornare faucibus. Maecenas eget justo neque. Aenean condimentum vehicula eros vitae tincidunt. Maecenas eget metus odio. Nulla eu metus hendrerit, convallis massa et, iaculis dui. Nulla vel malesuada nunc. Praesent bibendum tristique lorem, et consequat nisl pharetra ut. In eget lorem vel tortor gravida fringilla sit amet eu lectus. Curabitur malesuada eleifend neque eu semper.',
		
		'Suspendisse lectus lorem, aliquet id pellentesque sit amet, ultricies vitae elit. Cras molestie, tellus sit amet condimentum aliquam, sapien ex volutpat metus, nec molestie nulla ante et nisl. In nec purus libero. Donec sit amet lectus ex. Duis congue volutpat nulla, sit amet cursus diam aliquam in. Sed urna tellus, vulputate id dolor ac, facilisis pellentesque ante. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In luctus tortor quis risus convallis mattis.',
	]

	return (
		<>
			{loremIpsum.slice(0, paragraphs).map(paragraph => <p key={paragraph.slice(0, 24)}>{paragraph}</p>)}
		</>
	)
}

export default LoremIpsum
